apiVersion: v1
kind: Service
metadata:
  name: anomaly-api-service

spec:
  type: NodePort   # exposes service outside Minikube cluster

  selector:
    app: anomaly-api

  ports:
    - protocol: TCP
      port: 8000        # internal cluster port
      targetPort: 8000  # container port
      nodePort: 30007   # external access port (fixed range 30000-32767) 